#!/usr/bin/env python3
"""
スプレッドシート手動作成ガイド
"""

import os
from dotenv import load_dotenv

load_dotenv()

spreadsheet_id = os.getenv('SPREADSHEET_ID')

print("=" * 60)
print("📋 スプレッドシート手動作成ガイド")
print("=" * 60)
print()
print("⚠️  project_goal シートへの自動書き込みが失敗しました")
print("    シートが存在しないか、権限が不足している可能性があります")
print()
print("🔧 手動作成手順:")
print()
print(f"1. スプレッドシートを開く:")
print(f"   https://docs.google.com/spreadsheets/d/{spreadsheet_id}")
print()
print("2. 画面下部の「+」ボタンをクリック")
print()
print("3. 新しいシートを3つ作成し、それぞれ以下の名前に変更:")
print("   - project_goal")
print("   - pm_tasks")
print("   - task_execution_log")
print()
print("4. 各シートの1行目（ヘッダー）に以下を入力:")
print()
print("   【project_goal】")
print("   A1: goal_id")
print("   B1: description")
print("   C1: priority")
print("   D1: status")
print("   E1: created_at")
print()
print("   【pm_tasks】")
print("   A1: task_id")
print("   B1: parent_goal_id")
print("   C1: description")
print("   D1: required_role")
print("   E1: status")
print("   F1: priority")
print("   G1: estimated_time")
print("   H1: dependencies")
print("   I1: created_at")
print("   J1: batch_id")
print()
print("   【task_execution_log】")
print("   A1: task_id")
print("   B1: status")
print("   C1: output")
print("   D1: executed_at")
print("   E1: knowledge_used")
print()
print("=" * 60)
print("✅ 作成完了後、以下を実行してください:")
print("   python3 test_orchestrator_5min.py")
print("=" * 60)
