#!/bin/bash
# ==
# ダッシュボード起動コマンド一覧
# ==

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ダッシュボード起動コマンド一覧"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【基本コマンド】"
echo ""
echo "1. ダッシュボード起動:"
echo "   bash sh/start_dashboard.sh"
echo ""
echo "2. ダッシュボード停止:"
echo "   bash sh/stop_dashboard.sh"
echo ""
echo "3. ページ確認:"
echo "   bash sh/check_dashboard_pages.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【アクセスURL】"
echo ""
echo "メインダッシュボード:"
echo "   http://localhost:5000/"
echo ""
echo "依存関係グラフ:"
echo "   http://localhost:5000/dependencies"
echo ""
echo "問題検出:"
echo "   http://localhost:5000/analysis"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【GitHub Codespaces環境での手順】"
echo ""
echo "1. VSCodeの「ポート」タブを開く"
echo "2. ポート5000の地球儀🌐アイコンをクリック"
echo "3. ブラウザで開く"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
