#!/bin/bash
echo "=================================="
echo "🤖 自律型エージェントシステム"
echo "=================================="
echo ""
echo "📦 コアシステム:"
echo "  ├─ test_tasks_practical.py      # 実践的タスク実行"
echo "  ├─ integrated_autonomous_system_v2.py  # 統合自律システム"
echo "  ├─ continuous_monitor.py        # 継続監視"
echo "  └─ main_hybrid_fix.py           # 自動修正"
echo ""
echo "🔧 サブシステム:"
echo "  ├─ wordpress/wp_agent.py        # WordPress統合"
echo "  ├─ sheets_manager.py            # Google Sheets連携"
echo "  ├─ browser_controller.py        # ブラウザ自動化"
echo "  └─ task_executor/               # タスク実行エンジン"
echo ""
echo "📊 データ管理:"
echo "  ├─ error_logs/*.json            # エラーログ"
echo "  └─ logs/stats_*.json            # 実行統計"
echo ""
echo "=================================="
echo "✅ 全システム動作中"
echo "=================================="
