<?php
// Auto-generated by WordPress Dev Framework


// カスタム投稿タイプ: ma_company
function ma_company_register_post_type() {
    register_post_type('ma_company', array(
        'labels' => array(
            'name' => 'M&A企業情報',
            'singular_name' => '企業情報',
        ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-building',
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'show_in_rest' => true,
    ));
}
add_action('init', 'ma_company_register_post_type');


// タクソノミー: ma_industry
function ma_industry_register_taxonomy() {
    register_taxonomy('ma_industry', 'ma_company', array(
        'labels' => array(
            'name' => '業種',
        ),
        'hierarchical' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));
}
add_action('init', 'ma_industry_register_taxonomy');

