#!/bin/bash
echo "🚀 GitHub Actionsキャッシュクリーンアップを手動実行"
echo "📋 実行方法:"
echo "1. GitHubリポジトリの 'Actions' タブを開く"
echo "2. 'Clean Cache on Code Execution' ワークフローを選択"
echo "3. 'Run workflow' ボタンをクリック"
echo "4. ブランチを選択して実行"
echo ""
echo "🌐 GitHub URL:"
echo "https://github.com/$(git remote get-url origin | sed 's/.*github.com[:/]//' | sed 's/\.git$//')/actions"
